### ISSUE TITLE
Data setovi

### ISSUE THREAD

**Issue by AlexSensei** [AlexSensei/NoSQL#1]
Posto radimo 4 odvojena data seta neka svako nadje sta ce da uradi i neka postavi u komentar.
Djole svoje
Mira i Nikola svoje
Milica i Nemanja svoje
Dara i ja svoje

**Comment by MirjanaLakic** [comment]
Nikola i ja radimo sa data setom koji vodi evidenciju o tome koliko su zivotinje u opasnosti od drugih zivotinja

**Comment by DaraYo** [comment]
Vodostaj reke Amazon u zavisnosti od kolicine padavina tokom godina

**Comment by FoxGrayy** [comment]
Nemanja i ja koristimo data setove koji prikazuju rasprostrajenost komaraca  i malarije po  drzavama.

**Comment by Gambit88** [comment]
Vinogradi,proizvodnja i potrosnja vina (2011-2014).
